import React from 'react'
import {Container, Row, Col} from "react-bootstrap"

const About = () => {
  return (
   <>
   <Container style = {{marginTop: "50px"}}>
        <h1>Qui sommes-nous ?</h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corporis fugiat id libero laudantium minus. Repellat, non voluptatibus odio impedit ipsum iste voluptatem voluptates aspernatur, dignissimos veritatis maiores nulla magnam consequuntur quod ipsam asperiores veniam alias. Quasi suscipit explicabo vel architecto optio voluptatibus cum, at sed similique tempore eos officia alias cupiditate possimus sapiente amet enim perspiciatis fuga impedit aut libero nesciunt sit dolores soluta? Rerum enim officiis reprehenderit cum laboriosam quod ratione minus necessitatibus voluptatum, maxime dolorem fuga deleniti veritatis, eaque ut cupiditate, odio fugit nesciunt! Recusandae excepturi ducimus tenetur aut dolore aliquam laborum unde neque, nesciunt nulla quod veniam quidem adipisci! Recusandae, aperiam? Assumenda magnam beatae enim! At iure doloremque, unde, blanditiis recusandae, vero molestias corporis modi incidunt numquam pariatur vitae eveniet omnis accusamus beatae qui magnam accusantium distinctio. Ipsum veritatis sed temporibus provident tenetur voluptas rerum est quae porro pariatur beatae repudiandae commodi quia qui, eveniet error! Veniam laborum praesentium eius amet est voluptates impedit quibusdam? Maxime consequatur est incidunt amet quaerat repellat. Aliquid minus, corrupti laborum quos eligendi optio? Nisi, dolorum dignissimos! Cupiditate nam cum rerum accusamus sequi impedit quisquam facere, dolor odit, doloribus itaque. Laudantium itaque reiciendis quia sit nihil, consequatur unde odio veniam eum magni.</p>
        <h1>Notre spécialté</h1>
        <Row>
            <Col md={6}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate ipsum impedit delectus est? Architecto est ut beatae nisi iste facere. Sunt velit amet aliquam et recusandae ratione illo modi corrupti laboriosam, laborum a at cumque facilis omnis quisquam dignissimos itaque eum deserunt voluptates totam pariatur ad porro quaerat illum! Blanditiis earum officia esse voluptates fugit expedita obcaecati dicta a! Explicabo fugiat sunt eos sapiente soluta, nisi quos accusantium expedita eaque inventore veritatis et, exercitationem dolores ipsam commodi cumque alias nam ducimus? Perspiciatis quia voluptatem eligendi quisquam excepturi exercitationem iste voluptate tenetur rerum, obcaecati at officia sequi vero fuga incidunt, nam cumque doloribus accusantium dicta iure. Dolorum excepturi tempore architecto non debitis voluptate alias. Qui, voluptatibus necessitatibus molestiae similique, maxime earum quia illo, aperiam corrupti delectus ullam? Aliquam qui doloremque ullam vero nulla sunt provident similique numquam quisquam iste sit eligendi nisi commodi quaerat, fuga vitae. Eligendi dolorem, animi magni expedita dignissimos inventore, harum numquam quibusdam sequi sapiente aliquam molestiae iure recusandae! Doloribus vero inventore minima tempore laudantium! Laudantium commodi, aut accusamus et rem ut iusto inventore debitis dolore voluptas libero. Numquam illum molestiae, animi, voluptates odit consequatur possimus laboriosam aperiam deserunt itaque ad blanditiis, ipsum ea placeat at. Excepturi, perferendis.</p>
            </Col>
            <Col md={6}>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos excepturi illo sapiente at qui tenetur saepe, non nam soluta, nobis dicta! Quis quos, vitae voluptatem consectetur quidem quia, exercitationem praesentium fugiat molestiae aperiam laborum quam officia? Beatae ut soluta vero eligendi dicta nulla ullam dolorem, temporibus quos odit voluptas placeat vel! Laboriosam in praesentium facilis? Beatae fugit officiis tempora deleniti neque possimus, rerum modi iste aperiam nam corrupti dignissimos doloribus illo quam eaque ea laborum? Hic, cupiditate dignissimos recusandae labore dolorem incidunt dolor laboriosam aliquid voluptate ipsa animi omnis veritatis nemo temporibus iure quis earum voluptatum tempora culpa ipsum odit debitis voluptatibus nulla quidem! Dolor, veritatis voluptates! Velit quidem, rem voluptatum quas sapiente eveniet mollitia, soluta iste assumenda recusandae quam nulla tenetur maxime incidunt architecto quisquam libero quo iusto quia earum nemo hic error repudiandae natus! Non dolore repudiandae esse, possimus enim architecto repellat earum nemo corrupti. Magni iusto, perspiciatis atque mollitia dolorum, laboriosam laudantium laborum veniam aliquam, nisi placeat quia odit iure animi illum eum omnis ea odio corporis quod accusantium est quos. At molestias facere aperiam aliquam dignissimos nulla ipsa sequi voluptatibus, cum repellat explicabo quod quis. Animi voluptate aliquam debitis. Velit incidunt quos suscipit quas dolor aliquam.</p>
            </Col>
        </Row>
        <Row>
            <h1>Le Chef</h1>
            <Col md={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores eos magni, cumque blanditiis excepturi veritatis, vitae qui sit recusandae aperiam officiis ullam, optio facilis voluptate corrupti omnis neque! Blanditiis animi numquam reprehenderit quasi perspiciatis ut maxime neque nihil quos a, eligendi, minus quia tempora officia quam hic ducimus dicta eum voluptas nemo. Tenetur molestias at aperiam tempora, nihil sunt. Impedit incidunt, ea similique temporibus necessitatibus quae iste quibusdam architecto minima quaerat, vero unde aut facilis dolorem voluptatem quam itaque neque porro! Soluta nisi voluptas sapiente, excepturi ratione nemo qui hic ab dignissimos quam odio. Enim magnam cupiditate assumenda voluptate quaerat?</p>
            </Col>
            <Col md ={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ex, cum, provident dolore, facilis numquam perspiciatis delectus dicta recusandae soluta consectetur fugiat non officia voluptas rerum quas accusamus illum ad ipsum hic eveniet aliquid aperiam? Voluptatibus, deserunt sapiente a atque, laudantium voluptatum odio cumque aliquam ipsa ex eum hic vel quia. Voluptate, doloremque. Possimus aspernatur quibusdam illo, commodi cupiditate quasi autem doloribus porro libero deserunt maiores, enim hic tenetur! Minus, hic harum laudantium sint officia dignissimos dolorem dolore rem voluptatum aperiam earum, recusandae itaque rerum deserunt ad odio architecto eligendi praesentium ab minima quaerat officiis illum! Cumque necessitatibus saepe omnis!</p>
            </Col>
            <Col md ={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ex, cum, provident dolore, facilis numquam perspiciatis delectus dicta recusandae soluta consectetur fugiat non officia voluptas rerum quas accusamus illum ad ipsum hic eveniet aliquid aperiam? Voluptatibus, deserunt sapiente a atque, laudantium voluptatum odio cumque aliquam ipsa ex eum hic vel quia. Voluptate, doloremque. Possimus aspernatur quibusdam illo, commodi cupiditate quasi autem doloribus porro libero deserunt maiores, enim hic tenetur! Minus, hic harum laudantium sint officia dignissimos dolorem dolore rem voluptatum aperiam earum, recusandae itaque rerum deserunt ad odio architecto eligendi praesentium ab minima quaerat officiis illum! Cumque necessitatibus saepe omnis!</p>
            </Col>
            <Col md ={3}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ex, cum, provident dolore, facilis numquam perspiciatis delectus dicta recusandae soluta consectetur fugiat non officia voluptas rerum quas accusamus illum ad ipsum hic eveniet aliquid aperiam? Voluptatibus, deserunt sapiente a atque, laudantium voluptatum odio cumque aliquam ipsa ex eum hic vel quia. Voluptate, doloremque. Possimus aspernatur quibusdam illo, commodi cupiditate quasi autem doloribus porro libero deserunt maiores, enim hic tenetur! Minus, hic harum laudantium sint officia dignissimos dolorem dolore rem voluptatum aperiam earum, recusandae itaque rerum deserunt ad odio architecto eligendi praesentium ab minima quaerat officiis illum! Cumque necessitatibus saepe omnis!</p>
            </Col>
        </Row>
   </Container>
   </>
  )
}

export default About;